### ISSUE TITLE
Arreglar fallos visuales

### ISSUE THREAD

**Issue by Peleato** [UNIZAR-30226-2020-01/frontend_web#34]
- Cards largas en pantalla de albums
- Colores enlace podcast
- Cards en podcast indv blancas
- Colores reproductor
- Dejar pantalla de playlist igual que la de albumIndv
- Desplegable de add to playlist (es transparente)
- Botón del reproductor más grande
- Botón de reproducción cuando clicas en foto en más lugares

**Comment by Haz99** [comment]
Todo perfecto :D
